Reset cmd when a transaction gets changed
kadena-community/kadena.js pull request #112
Opened 2022-12-05 12:21 UTC by ashwinvandijk

2022-12-07 10:58 UTC, Randynamic approved these changes

2022-12-07 13:41 UTC, Randynamic approved these changes

2022-12-07 14:00 UTC, Randynamic submitted a review, later dismissed

2022-12-07 14:03 UTC, alber70g approved these changes
Minor comment

2022-12-07 14:03 UTC, alber70g commented on packages/libs/client/src/tests/pact.test.ts
> +  describe('unfinishes the transaction', () => {
`describe` contains the subject, `it` contains the action that is executed and the result that it should yield

I this case `describe('Pact proxy')` `it('unfinishes the transaction when setMeta is called')`

gives this sentence: `Pact proxy unfinishes the transaction when setMeta is called`

2022-12-07 14:12 UTC, alber70g commented on CODEOWNERS
> +./*.*       @alber70g @randynamic @ggobugi27 @ashwinvandijk
Not sure if this is necessary. We're not working with this yet... 
The plan was to add codeowners for specific projects.
I would probably be codeowner for the `./common` as that is rush stuff

2022-12-13 21:25 UTC, Randynamic submitted a review, later dismissed

2022-12-14 10:53 UTC, alber70g requested changes

2022-12-14 10:53 UTC, alber70g commented on packages/libs/client/src/tests/pact.test.ts
> +describe('The hash and signers for a transaction are reset', () => {
```suggestion
describe('TransactionCommand', () => {
```

2022-12-14 10:53 UTC, alber70g commented on packages/libs/client/src/tests/pact.test.ts
> +  it('when setMeta is called', async () => {
```suggestion
  it('resets `cmd` `hash` and `signatures` when `setMeta` is called', async () => {
```

2022-12-14 10:53 UTC, alber70g commented on packages/libs/client/src/tests/pact.test.ts
> +  it('when addData is called', async () => {
```suggestion
  it('resets `cmd` `hash` and `signatures` when `addData` is called', async () => {
```

2022-12-14 10:53 UTC, alber70g commented on packages/libs/client/src/tests/pact.test.ts
> +  it('when addCap is called', async () => {
```suggestion
  it('resets `cmd` `hash` and `signatures` when `addCap` is called', async () => {
```

2022-12-14 10:53 UTC, alber70g commented on common/changes/@kadena/client/feat-remove-cmd-malleable_2022-12-05-12-16.json
> +      "comment": "Remove `cmd` from the transaction when the properties of this transaction change, so it gets recalculated. Also reset signatures (if any) in that case, because the signatures do no
```suggestion
      "comment": "When proprerties of a non-malleable transaction change, remove `cmd`, `hash` and `signatures` from the transaction to issue a recalculation of the `cmd` and `hash`.",
```

2022-12-14 13:43 UTC, alber70g approved these changes

2022-12-14 13:44 UTC, merged