[libs/client] Add chainwebjs to kadenajs
kadena-community/kadena.js pull request #130
Opened 2022-12-16 14:23 UTC by nillo

## Reason: Added type support for chainwebJS, reason types where missing. enables chainwebJS to be part of kadenaJS until new api has been created, and a replacement package for chainweb has to be written. 

* This package is a temporary solution and will be deprecated once the new version for the new api comes out.
* Minimal code tweaks have been made to original, mostly types added in agreement with randy

## Changes made (preferably with images/screenshots):

## Check off the following:

- [x] I have reviewed my changes and run the appropriate tests.
- [x] I have have run `rush change` to add the appropriate change logs.
- [x] I have added/edited docs.
- [x] I have added tutorials.
- [x] I have double checked and DEFINITELY added docs.

2023-01-18 12:34 UTC, ash-vd approved these changes

2023-01-18 12:34 UTC, ash-vd commented on packages/libs/chainwebjs/src/paging.ts
> +/* Pageing Tools */
```suggestion
/* Paging Tools */
```

2023-01-18 13:20 UTC, alber70g requested changes

2023-01-18 13:20 UTC, alber70g commented on packages/libs/chainwebjs/src/tests/mocks/360hashes.ts
> +/* eslint-disable max-lines */
Let's add the `tests/mocks` directory to `packages/libs/chainwebjs/.eslintignore`

2023-01-18 13:20 UTC, alber70g commented on packages/libs/chainwebjs/src/tests/retries.test.ts
> +  test('retry 404', async () => {
Can we change all `test` to `it`?
Convention is to use `describe-it` syntax.

2023-01-18 13:20 UTC, alber70g commented on packages/libs/chainwebjs/src/tests/transactions.test.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
Idem

2023-01-18 13:20 UTC, alber70g commented on packages/libs/chainwebjs/src/tests/transactions.test.ts
> +
The describes in this file should probably be wrapped in a

`describe('chainweb.transactions`, () => {`

with `it`s being what is now in the current `describe`s

2023-01-18 13:20 UTC, alber70g commented on packages/libs/chainwebjs/src/transactions.ts
> +  return filterTxs(x);
Let's give the `x` a meaningful name

2023-01-18 13:20 UTC, alber70g commented on packages/libs/chainwebjs/tsconfig.json
> +    "types": ["heft-jest", "node"],
Can we get rid of "node". The lib should work in a browser environment as well. Is that possible? See also #47

2023-01-18 13:21 UTC, KdWarlordz commented on packages/libs/chainwebjs/src/config.ts
> +};
i like this, will do

2023-01-23 16:24 UTC, alber70g approved these changes

2023-01-24 09:07 UTC, ash-vd approved these changes

2023-01-24 09:07 UTC, merged