Update the namespace tutorial in the election app workshop series.
kadena-community/kadena.js pull request #1378
Opened 2023-12-20 23:21 UTC by lsgunnlsgunn

2023-12-22 12:42 UTC, alber70g approved these changes
Minor comment

2023-12-22 12:42 UTC, alber70g commented on .vscode/settings.json
> +  ]
We have a (unwritten) convention to only add technical settings here that are required for certain extensions to work properly. 

Could you move this to your user setting? 

[User/Workspace settings](https://code.visualstudio.com/docs/getstarted/settings)
* [User settings](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations)
* [Workspace settings](https://code.visualstudio.com/docs/getstarted/settings#_workspace-settingsjson-location)

2024-01-06 15:13 UTC, Randynamic approved these changes

2024-01-10 21:35 UTC, Ghislain89 requested changes

2024-01-10 21:35 UTC, Ghislain89 commented on .vscode/settings.json
> -}
I'm not entirely sure this file should be deleted. @alber70g , I was under the impression it was needed?

2024-01-11 16:58 UTC, Ghislain89 approved these changes

2024-01-12 18:12 UTC, merged