Update the keyset tutorial in the election workshop
kadena-community/kadena.js pull request #1392
Opened 2023-12-22 21:57 UTC by lsgunnlsgunn

2024-01-03 12:36 UTC, Randynamic approved these changes

2024-01-10 21:34 UTC, Ghislain89 requested changes

2024-01-10 21:34 UTC, Ghislain89 commented on packages/apps/docs/.changeset/lucky-teachers-roll.md
> +---
You should be able to delete this file and the `.changeset` folder in the path /packages/apps/docs.  The `.changeset` folder should only exist in the root of the repository

2024-01-11 08:27 UTC, Ghislain89 approved these changes

2024-01-12 19:17 UTC, closed without merging