Fix/using new icons
kadena-community/kadena.js pull request #1849
Opened 2024-03-19 13:26 UTC by ferreroltd

This PR is meant to remove the old SystemIcon with the new product design icons, it impacts a little bit the appearance of some icons and a little bit the api of some interfaces, please verify

2024-03-19 13:27 UTC, ferreroltd commented
Currently checking why the /faucet is not rendering the side navigation

2024-03-22 14:46 UTC, KristinaSpasevska requested changes
These icons stay with these colors?

<img width="330" alt="Screenshot 2024-03-22 at 15 35 22" src="https://github.com/kadena-community/kadena.js/assets/132443209/39fe87f3-994d-4a8e-9b90-b084465713d5">
<img width="753" alt="Screenshot 2024-03-22 at 15 36 37" src="https://github.com/kadena-community/kadena.js/assets/132443209/1f5be125-0514-4532-b447-34b29327214f">
<img width="736" alt="Screenshot 2024-03-22 at 15 44 29" src="https://github.com/kadena-community/kadena.js/assets/132443209/8aa995f0-b67f-4c52-8fd7-e092a595f1bf">

2024-03-22 15:01 UTC, isaozler commented
> These icons stay with these colors?

The icons should have the following tokens assigned based on the feature/functionality. 

**Default Icons / Fallback**
`kda.foundation.color.icon.base.default`

**Brand Icons**
`kda.foundation.color.icon.brand.primary.default`
`kda.foundation.color.icon.brand.secondary.default`

**Semantic Icons**
`kda.foundation.color.icon.semantic.positive.default`
`kda.foundation.color.icon.semantic.negative.default`
`kda.foundation.color.icon.semantic.warning.default`
`kda.foundation.color.icon.semantic.info.default`

2024-03-22 15:02 UTC, isaozler commented
@KristinaSpasevska does this ⬆️ help?

2024-03-25 08:52 UTC, sanderlooijenga commented on packages/apps/tools/src/components/Common/Layout/partials/Sidebar/styles.css.ts
> +    height: '16px',
Can we get these values from tokens?

2024-03-25 12:38 UTC, sanderlooijenga approved these changes

2024-03-25 13:21 UTC, KristinaSpasevska approved these changes

2024-03-25 13:21 UTC, merged