Feat/icons
kadena-community/kadena.js pull request #223
Opened 2023-04-11 08:22 UTC by EnoF

## Reason:

Add Icon variants for size and colors

## Changes made (preferably with images/screenshots):
![image](https://user-images.githubusercontent.com/1508400/231100427-f6318d2c-377b-424e-b4fa-f9b03bd72e21.png)
![image](https://user-images.githubusercontent.com/1508400/231100490-62370a1b-de0f-4a8c-bca5-ba6869e1db61.png)
![image](https://user-images.githubusercontent.com/1508400/231100549-f1efdc93-934b-4dcc-84a3-1ce4f9f023bf.png)

## Check off the following:

- [ ] I have reviewed my changes and run the appropriate tests.
- [ ] I have have run `rush change` to add the appropriate change logs.
- [ ] I have added/edited docs.
- [ ] I have added tutorials.
- [ ] I have double checked and DEFINITELY added docs.

2023-04-11 08:28 UTC, isaozler approved these changes

2023-04-11 08:57 UTC, sstraatemans approved these changes

2023-04-11 09:02 UTC, eileenmguo requested changes
A couple of comments!

- I think the icon files should be capitalized since they are component files
- I'm a bit confused as to how the svgs have changed to accept the color. It looks like they have all been updated to have the svg accept the color prop and removed the fill/stroke from the children. I would have suggested to just update all of the stroke/fill colors from  "black" to "currentColor" so it's very explicit how the color is being applied and the color itself is cascaded from the parent: https://css-tricks.com/cascading-svg-fill-color/ . This means that the color can be optional and the svg will default to black. What is the reason for going for this other approach?

2023-04-11 10:43 UTC, EnoF commented on packages/libs/react-components/src/components/Icons/index.tsx
> +  color?: keyof typeof colorVariant;
I've refactored it to use the `css` override and changed all the svg's to accept the inherrited color

2023-04-11 10:43 UTC, EnoF commented on packages/libs/react-components/src/components/Icons/Icon.stories.tsx
> +    color: {
removed this variant

2023-04-12 13:06 UTC, eileenmguo commented on packages/libs/react-components/src/components/Icons/Icon.stories.tsx
> +      options: ['sm', 'md', 'lg'],
nitpick: Would be better to get these from the variant object so if it ever changes this will automatically get updated

2023-04-13 09:53 UTC, eileenmguo approved these changes
🥳

2023-04-13 11:57 UTC, merged