Update storage.md
kadena-community/kadena.js pull request #2300
Opened 2024-06-19 13:26 UTC by pascaljb

Updating the section in Akord in line with recent updates to our app, API and docs.

2024-06-24 15:03 UTC, lsgunnlsgunn commented
Hi @pascaljb, I put in the requested changes without knowing there was a PR open for it (I was given a link to a Google doc with the changes instead). Sorry for any confusion. Closing this PR as no longer necessary.

2024-06-24 15:49 UTC, pascaljb commented
Hi @lsgunnlsgunn these changes are the latest, in line with very recent updates to the app and API. I believe the Google docs is from a few months ago and the content is out of date. Could we update with this content for the Akord section? Thanks

2024-06-24 19:48 UTC, lsgunnlsgunn requested changes
Sorry, I thought this was old one. Can we do something different with the numbering other than 1, 1a, 1b, etc.? It isn't a convention used anywhere else in the doc so it seems a little odd.

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +### 1. Upload the image asset to Arweave
```suggestion
### Upload assets with the Akord app
```

I might suggest getting rid of empty headings and bump up the content a heading level and use numbered steps for steps.

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +**1a. Upload with the Akord app**
```suggestion
```
This doesn't quite seem necessary to me.

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +You get 100 MB free on sign up and can easily upload in a few minutes using the web app. [Sign up](https://v2.akord.com/signup), login and follow the instructions to create an “NFT assets” vault.
```suggestion
You get 100 MB free on sign up and can easily upload in a few minutes using the web app. 

1. [Sign up](https://v2.akord.com/signup), login and follow the instructions to create an “NFT assets” vault. 
```

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +Upload your file to the vault and wait for it to be successfully committed on the Arweave blockchain, normally 5-15 minutes.
```suggestion
2. Upload your file to the vault and wait for it to be successfully committed on the Arweave blockchain, normally 5-15 minutes. 
```

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +**1b. Upload with the Akord API**
```suggestion
### Upload with the Akord API
```

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +- [First, create your account in seconds](https://v2.akord.com/signup) (100 MB free to test your workflow)
```suggestion
1. Create your account in seconds](https://v2.akord.com/signup) (100 MB free to test your workflow).
```

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +- [Next, get your API key here](https://v2.akord.com/account/developers)
```suggestion
2. Get your [API key here](https://v2.akord.com/account/developers).
```

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +**1c. Upload by with Akord CLI**
```suggestion
### Upload with Akord CLI
```

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +### 2. Get the Arweave gateway URL
```suggestion
### Get the Arweave gateway URL
```

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +**2a. Single NFT**
```suggestion
#### Single NFT
```

2024-06-24 19:48 UTC, lsgunnlsgunn commented on packages/apps/docs/src/docs/build/nft-marmalade/storage.md
> +**2b. NFT Collection**
```suggestion
#### NFT collection
```

2024-06-24 20:10 UTC, pascaljb commented
@lsgunnlsgunn totally, happy to go with whatever you think makes sense on the headings in the context of the styles you have. Thanks!

2024-06-24 23:02 UTC, lsgunnlsgunn commented
@pascaljb cool. I'll approve and merge these tomorrow. Thanks for your patience!  There's a lot to keep track of with our fledgling docs site 😆.

2024-06-25 15:22 UTC, lsgunnlsgunn approved these changes

2024-07-01 18:12 UTC, closed without merging