hd-wallet  - cleanup docs to match wallet-sdk
kadena-community/kadena.js pull request #2660
Opened 2024-11-12 15:40 UTC by nillo

added updated docs for hd-wallet to align with wallet-sdk

2024-12-05 11:13 UTC, Randynamic approved these changes

2024-12-05 11:13 UTC, Randynamic commented
@lsgunnlsgunn can we check this and merge?

2024-12-06 09:14 UTC, barthuijgen approved these changes

2024-12-09 08:53 UTC, javadkh2 requested changes

2024-12-09 08:53 UTC, javadkh2 commented on packages/libs/hd-wallet/README.md
> +- **Seed**: A binary representation of the mnemonic, which can be used to derive
this is not correct! *Entropy* is the representation of the mnemonic not seed. 
Seed is a binary derived from mnemonic (with a hashing algorithm) will be used for creating master private key. Basically you can't generate mnemonic from a seed but you can create it from Entropy.

2024-12-09 08:53 UTC, javadkh2 commented on packages/libs/hd-wallet/README.md
> +## Legacy Chainweaver Support
## Legacy Chainweaver (version 2) Support
```suggestion
## Legacy Chainweaver (version 2) Support
```

2024-12-09 08:53 UTC, javadkh2 commented on packages/libs/hd-wallet/README.md
> +The Kadena wallet uses the standard derivation path:
add link to "packages/libs/hd-wallet/docs/decisions/0001-use-slip10-for-private-key-generation.md"

2024-12-09 09:15 UTC, barthuijgen commented on packages/libs/hd-wallet/README.md
> +
This does not seem directly related to hd-wallet, this should be documented with `@kadena/client` itself. or if using sdk methods in the `@kadena/wallet-sdk` docs.

2024-12-09 09:39 UTC, barthuijgen approved these changes

2024-12-09 09:43 UTC, javadkh2 approved these changes

2024-12-09 09:49 UTC, merged