Feat/button variants
kadena-community/kadena.js pull request #336
Opened 2023-05-30 09:26 UTC by rezaerami

## Reason: feat(button): add new variants

Closes [issue link]

## Changes made (preferably with images/screenshots):
- add positive and secondary variants to button

## Check off the following:

- [ ] I have reviewed my changes and run the appropriate tests.
- [ ] I have have run `rush change` to add the appropriate change logs.
- [ ] I have added/edited docs.
- [ ] I have added tutorials.
- [ ] I have double checked and DEFINITELY added docs.

2023-05-30 12:43 UTC, sstraatemans commented
lots of files in this PR, which are already merged in Master.
I think your branch not up to date.

no idea if the colours are approved by @isaozler 
if they are I approve the PR

2023-05-30 12:43 UTC, sstraatemans requested changes
can you get the branch up to date?

2023-06-02 08:27 UTC, isaozler commented
@eileenmguo I remember the colors were fixed for the button component. Wasn't it? 😕

2023-06-06 12:16 UTC, eileenmguo approved these changes

2023-06-06 12:16 UTC, eileenmguo commented on packages/libs/react-components/src/components/Button/Button.stories.tsx
> +      options: ['primaryFilled', 'secondaryFilled', 'positiveFilled'],
nit: You can take the keys from the variant object so that they don't get out of sync when adding/removing variants

2023-06-06 12:39 UTC, merged