Enable safe transfer
kadena-community/kadena.js pull request #340
Opened 2023-05-31 14:08 UTC by KristinaSpasevska

## Reason:

Closes [issue link]

## Changes made (preferably with images/screenshots):

## Check off the following:

- [ ] I have reviewed my changes and run the appropriate tests.
- [ ] I have have run `rush change` to add the appropriate change logs.
- [ ] I have added/edited docs.
- [ ] I have added tutorials.
- [ ] I have double checked and DEFINITELY added docs.

2023-05-31 14:29 UTC, nil-amrutlal-dept commented
I've made some changes to the existing variable names and also to the structure of the code on my cross-chain transfer branch. Since I am not able to complete the transfer yet, I'd say we can merge this one when ready and then I can refine everything (there will probably be conflicts).

2023-06-01 08:16 UTC, nil-amrutlal-dept approved these changes

2023-06-01 13:05 UTC, alber70g requested changes
Some comments

2023-06-01 13:05 UTC, alber70g commented on packages/apps/transfer/src/services/transfer/coin-transfer.ts
> +  )})`;
In the implementation of `convertDecimal` it'd be also better to use either `{ decimal: "10.0" }` or PactNumber or BigNumber

2023-06-01 13:05 UTC, alber70g commented on packages/apps/transfer/src/services/transfer/coin-transfer.ts
> +    .addCap(
Is it on purpose that only `x:y` type accounts are allowed? There can be named accounts that don't have the prefix `x:` (`x` being anything)

2023-06-01 13:05 UTC, alber70g commented on packages/apps/transfer/src/services/transfer/coin-transfer.ts
> +      Number(amountWithExtra),
Idem

2023-06-01 13:05 UTC, alber70g commented on packages/apps/transfer/src/services/transfer/coin-transfer.ts
> +  }
The sender and receiver could be signed in a separate process where the transaction from `createCommand()` could be sent to the other person via an async process. 
Does the feature allow for that use case?

2023-06-21 08:23 UTC, MRVDH commented
Note: PR on hold since it was decided not to do transfers in the dev tooling website yet.

2023-07-24 11:51 UTC, closed without merging