Box Component
kadena-community/kadena.js pull request #433
Opened 2023-06-16 19:35 UTC by bearni95

## Reason:

Closes ["Box Component"](https://app.asana.com/0/1204649083736950/1204549680288790/f)

## Changes made (preferably with images/screenshots):
- Primitive layout component that gives access to design tokens for margin

## Check off the following:

- [x] I have reviewed my changes and run the appropriate tests.
- [ ] I have have run `rush change` to add the appropriate change logs.
- [x] I have added/edited docs.
- [x] I have added tutorials.
- [x] I have double checked and DEFINITELY added docs.

2023-06-21 13:06 UTC, eileenmguo requested changes
I think there may have been some miscommunication about this component. Where are you getting the styles for this component from?

2023-06-21 13:06 UTC, eileenmguo commented on packages/libs/react-ui/src/components/Card/Card.css.ts
> +  sprinkles({ marginY: '$0' }),
I don't believe 0 needs the `$` prefix since it is a not a custom value

2023-06-21 21:49 UTC, bearni95 commented
As discussed, tried integrating a similar pattern to the one vanilla-extract uses for their own `<Box>` component. 

PR reverted to draft due to the experimental status of the current implementation

2023-06-22 08:11 UTC, eileenmguo approved these changes
This is super cool! I think it works great :)

2023-06-22 08:13 UTC, eileenmguo commented on packages/libs/react-ui/src/components/Box/Box.tsx
> +  right = undefined,
What is the reason for adding these?

2023-06-22 08:16 UTC, eileenmguo commented on packages/libs/react-ui/src/components/Box/Box.stories.tsx
> +  title: 'Layout/Vanilla Extract Box',
I would also change this to Layout/Box

2023-06-22 08:29 UTC, eileenmguo commented on packages/libs/react-ui/src/components/Box/Box.tsx
> +export interface IBoxProps extends Sprinkles {
Can we try making the type more strict? So there is a typescript error if anyone tries to pass in anything other than the margin props

2023-06-22 18:04 UTC, bearni95 commented on packages/libs/react-ui/src/components/Box/Box.tsx
> +  right = undefined,
Leftovers from testing, removed now

2023-06-23 10:07 UTC, eileenmguo approved these changes
Super excited about this one!

2023-06-23 18:48 UTC, merged