Add Pact Number functions
kadena-community/kadena.js pull request #51
Opened 2022-07-18 13:54 UTC by ggobugi27

- Renamed `mkPactInt` to `createPactInteger`, `mkPactDecimal` to `createPactDecimal`
- Added `Number.isInteger` check instead of `isSafeInteger` because Pact integers are not always safe integers. 
- Added `Number.isNaN` check.

2022-08-04 20:26 UTC, Randynamic approved these changes

2022-08-04 20:27 UTC, Randynamic commented
Looks good!!! @alber70g Can you check this as well so we can merge this PR?

2022-08-10 09:46 UTC, alber70g requested changes

2022-08-10 09:46 UTC, alber70g commented on packages/libs/kadena.js/src/util/PactNumber.ts
> +}
Should we move it to a separate lib? We have two categories, low level libs, and consumer libs. This could be part of a low-level lib?

2022-08-10 09:46 UTC, alber70g commented on packages/libs/kadena.js/src/util/tests/createExp.test.ts
> +});
Can you wrap these in `describe("createExp", () => { it("takes in a function...) } }`

2022-08-19 07:36 UTC, alber70g commented on rush.json
> +
Minuity: sorting in this file is done within the categories by `packageName`. So `@kadena/pactjs-utils` should be below `@kadena/integration-tests`

2022-08-19 07:37 UTC, alber70g submitted a review, later dismissed
Looks good!

2022-08-23 12:41 UTC, alber70g commented on packages/libs/pactjs-utils/tsconfig.json
> +    "types": ["heft-jest", "node"]
Does it work without "node"? We found out that adding this to the types, the libs potentially don't work when using in the browser.

2022-08-23 12:42 UTC, alber70g approved these changes

2022-08-24 11:19 UTC, merged