Fix/readme external sites
kadena-community/kadena.js pull request #63
Opened 2022-08-19 09:01 UTC by Randynamic

## Reason:

Closes [issue link]

## Changes made (preferably with images/screenshots):

## Check off the following:

- [ ] I have reviewed my changes and run the appropriate tests.

2022-08-22 09:37 UTC, alber70g requested changes

2022-08-22 09:37 UTC, alber70g commented on packages/libs/cryptography-utils/README.md
> +API Reference can be found here [ryptography-utils.api.md](https://github.com/kadena-community/kadena.js/tree/master/packages/libs/cryptography-utils/etc/cryptography-utils.api.md)
This is probably a typo?

2022-08-22 09:50 UTC, Randynamic commented on packages/libs/cryptography-utils/README.md
> +API Reference can be found here [ryptography-utils.api.md](https://github.com/kadena-community/kadena.js/tree/master/packages/libs/cryptography-utils/etc/cryptography-utils.api.md)
sharp

2022-08-24 13:34 UTC, alber70g approved these changes

2022-08-30 09:31 UTC, alber70g approved these changes

2022-08-30 12:12 UTC, merged